---
name: Run
on:
  workflow_dispatch:


jobs:
  triage:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    container:
      image: z-shell/zd
    steps:
         - name: Log the node version
           working-directory: .
           run: |
             docker run --rm --env --volume "${GIT_ROOT_DIR}:/src" \
             --volume "${TMPDIR:-/tmp}/ZZUnit:/data" --volume "${ROOT_DIR}/docker/zshenv:/home/z-dev/.zshenv" \
             --volume "${ROOT_DIR}/docker/zshrc:/home/z-dev/.zshrc"
             
