---
name: Run
on:
  workflow_dispatch:


jobs:
  triage:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    container:
      image: ghcr.io/z-shell/zd:latest
      volumes:
        - /home/runner/work/zd/zd:/src
        - /tmp/ZZUnit:/data  
    steps:
    - run: source ~/.zi/bin/zi.zsh && zi self-update
      shell: zsh {0}
